// AUTHENTICATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_ERROR = "GET_ALL_DATA_ERROR"; 
export const GET_ALL_DATA_REQUESTING = "GET_ALL_DATA_REQUESTING"; 



  


